name: aws-cni
namespace: kube-system
serviceType: managed

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

image:
  registry: quay.io
  name: giantswarm/aws-cni
  initName: giantswarm/aws-cni-init
  tag: v1.8.0
  pullPolicy: IfNotPresent

additionalTags: "{}"
warmIPTarget: "10"
minimumIPTarget: "40"
externalSNATEnabled: false
