version: 2.1
orbs:
  architect: giantswarm/architect@4.1.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          context: "architect"
          name: "package and push aws-cni chart"
          app_catalog: "default-catalog"
          app_catalog_test: "default-test-catalog"
          chart: "aws-cni"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
