apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
    name: aws-cni
spec:
    allowPrivilegeEscalation: true
    privileged: true
    allowedCapabilities:
      - 'NET_ADMIN'
    fsGroup:
      rule: RunAsAny
    runAsUser:
      rule: RunAsAny
    seLinux:
      rule: RunAsAny
    supplementalGroups:
      rule: RunAsAny
    hostNetwork: true
    hostPorts:
    - min: 0
      max: 65535
    volumes:
    - secret
    - configMap
    - hostPath
